
Showing logs for build [32mexplore-jenkinsx-python-flask-d-hg4wm-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-nhsx7[0m
{"level":"info","ts":1594427286.6824179,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1594427286.6828418,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mexplore-jenkinsx-python-flask-d-hg4wm-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-529wm[0m
{"level":"info","ts":1594427287.39456,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1594427287.396529,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mexplore-jenkinsx-python-flask-d-hg4wm-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mexplore-jenkinsx-python-flask-d-hg4wm-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-explore-jenkinsx-python-flask-d-hg4wm-pfxdq[0m
{"level":"info","ts":1594427323.464581,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1594427323.7038085,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/explore-jenkinsx/python-flask-docker.git @ v0.0.1 in path /workspace/source"}

Showing logs for build [32mexplore-jenkinsx-python-flask-d-hg4wm-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mexplore-jenkinsx-python-flask-d-hg4wm-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:703aa102907243b1ba80a67cce589ec23890b794
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mexplore-jenkinsx-python-flask-d-hg4wm-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mexplore-jenkinsx-python-flask-d-hg4wm-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mexplore-jenkinsx-python-flask-d-hg4wm-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "e2823688-976d-4deb-ba5b-cf1b43a3c0eb/explore-jenkinsx/python-flask-docker:0.0.1": resolving authorization for index.docker.io failed: error getting credentials - err: exec: "docker-credential-acr-linux": executable file not found in $PATH, out: ``
E0711 00:28:46.591198       9 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-build-container-build'. The execution of the pipeline has stopped.[0m
